# Generated by Django 3.2.4 on 2021-06-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route_planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollutionarea',
            name='name',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
