# Generated by Django 3.2.4 on 2021-06-19 13:11

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route_planner', '0003_alter_pollutionarea_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pollutionarea',
            old_name='created_at',
            new_name='measured_at',
        ),
        migrations.RemoveField(
            model_name='pollutionarea',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='pollutionarea',
            name='name',
        ),
        migrations.AddField(
            model_name='pollutionarea',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='pollutionarea',
            name='pollutant_concentration',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='pollutionarea',
            name='source',
            field=models.CharField(choices=[('TR', 'TROPOMI'), ('OM', 'Omi'), ('OT', 'Other')], default='TR', max_length=2),
        ),
    ]
