# Generated by Django 3.2.4 on 2021-06-19 14:37

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route_planner', '0004_auto_20210619_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=16)),
                ('risk', models.CharField(choices=[('HI', 'High'), ('MD', 'Medium'), ('LO', 'Low')], default='HI', max_length=2)),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326)),
            ],
        ),
    ]
